### ISSUE TITLE
question for GTM-SM face detector work

### ISSUE THREAD

**Issue by jsikyoon** [chenxy99/Generative-Temporal-Models-with-Spatial-Memory#2]
Hi Xianyu,

This is Jaesik Yoon on SAP Labs Korea as ML developer.

First of all, thank you for sharing your great work, reproducing GTM-SM.

I have a question for face detector work, you wrote in README.md.

In CelebA, aligned img size is 218*178.

You just resized aligned img from 218*178 to 32 x 32?

Best Regards,
Jaesik.

**Comment by chenxy99** [comment]
Yes, I preprocess the CelebA aligned images from 218x178 to 32x32 by using the matlab built-in functions  vision.CascadeObjectDetector() and insertObjectAnnotation. And for convenience, I save the preprocessed result in ./datasets/CelebA.zip. You can directly use it.

**Comment by jsikyoon** [comment]
OK Thanks!

I will close this issue !
