### ISSUE TITLE
Training not working well after wo_wall_and_penalty_end_epoch

### ISSUE THREAD

**Issue by junmokane** [chenxy99/Generative-Temporal-Models-with-Spatial-Memory#6]
Hi, chenxy99. 

I've read your code on GTM-SM which was very well-written and intuitive. Thanks.

While running the code, I observed that training after wo_wall_and_penalty_end_epoch did not work well.
wo_wall_and_penalty_end_epoch is the epoch that training_sigmoid is True, which means the state inference model additionally trains enc_st_sigmoid network. 
I've run total 100 epochs for the training, but the state inference model is not working well. (I've checked that before epoch wo_wall_and_penalty_end_epoch, state inference is working well)

I note that the trained model on github works well on both training_wo_wall = True and False cases.
I'm not sure what part is missing, should I run more epochs to get the result of given model on github?

Thanks.

**Comment by chenxy99** [comment]
Hello, junmokane,

I am sorry that I did not check this repo before and it takes a long time to reply to you. I wrote a [report](https://github.com/chenxy99/Generative-Temporal-Models-with-Spatial-Memory/blob/master/Report.pdf) 4 years ago, it demonstrates the motivation for why I need training_wo_wall and training_sigmoid. I hope the report can help to address your issue.

Best regards,
Xianyu
